/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-29 07:06:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.information;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import member.model.vo.Member;

public final class coronaInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1627487467283L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1627537908611L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("@@ -0,0 +1,216 @@\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>CoronaInfo</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= Favicon ================== -->\r\n");
      out.write("    <!-- Standard -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Styles -->\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 
	Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\r\n");
      out.write("		<div class=\"nano\">\r\n");
      out.write("			<div class=\"nano-content\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<div class=\"logo\">\r\n");
      out.write("						<a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\r\n");
      out.write("							<span>CovLab</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<li class=\"label\">Menu</li>\r\n");
      out.write("					<ul>                                                \r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">홈페이지</a></li>\r\n");
      out.write("						<li><a href=\"/semi/views/information/information.jsp\">뉴스/백신 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("						 \r\n");
      out.write("						");
 if(loginMember == null ){ //일반유져 
      out.write(" <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\r\n");
      out.write("						<li> <a href=\"/semi/views/member/enroll.html\">회원가입</a></li>\r\n");
      out.write("							\r\n");
      out.write("						");
 }else if(loginMember.getUserGrade().equals('A')){  //관리자 
      out.write("\r\n");
      out.write("						<li><a href=\"/semi/blistadmin?page=1\">접종 후기 관리</a></li>\r\n");
      out.write("						<li><a href=\"/semi/\">회원 관리</a></li> \r\n");
      out.write("                         ");
 }else {//로그인 
      out.write(" \r\n");
      out.write("                         <li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("						<li><a href=\"/semi/views/member/myInfo.jsp\">MY PAGE</a></li>\r\n");
      out.write("                         ");
 } 
      out.write("\r\n");
      out.write("							</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <ul>\r\n");
      out.write("					<li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\r\n");
      out.write("							Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"page-login.html\">Login</a></li>\r\n");
      out.write("							<li><a href=\"page-register.html\">Register</a></li>\r\n");
      out.write("							<li><a href=\"page-reset-password.html\">Forgot password</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"../documentation/index.html\"><i\r\n");
      out.write("							class=\"ti-file\"></i> Documentation</a></li>\r\n");
      out.write("					<li><a><i class=\"ti-close\" onclick=\"javascript:location.href='logout';\"></i> Logout</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /# sidebar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 
	Member loginMember1 = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 if(loginMember1 == null){ 
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"float-left\">\r\n");
      out.write("						<div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("							<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("								class=\"line\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"float-right\">\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-bell\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-email\"></i>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<span class=\"user-avatar\" onclick=\"javascript:location.href='/semi/views/member/login.jsp'\">로그인 해주세요\r\n");
      out.write("								</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"float-left\">\r\n");
      out.write("						<div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("							<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("								class=\"line\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"float-right\">\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-bell\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-email\"></i>\r\n");
      out.write("								<div class=\"drop-down dropdown-menu dropdown-menu-right\">\r\n");
      out.write("									<div class=\"dropdown-content-heading\">\r\n");
      out.write("										<span class=\"text-left\">2 New Messages</span> <a\r\n");
      out.write("											href=\"email.html\"> <i class=\"ti-pencil-alt pull-right\"></i>\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dropdown-content-body\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li class=\"notification-unread\"><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li class=\"notification-unread\"><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li class=\"text-center\"><a href=\"#\" class=\"more-link\">See\r\n");
      out.write("													All</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<span class=\"user-avatar\">");
      out.print( loginMember1.getUserId() );
      out.write("\r\n");
      out.write("								<i class=\"ti-angle-down f-s-10\"></i>\r\n");
      out.write("								</span>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\r\n");
      out.write("									<div class=\"dropdown-content-heading\">\r\n");
      out.write("										<span class=\"text-left\">Upgrade Now</span>\r\n");
      out.write("										<p class=\"trial-day\">30 Days Trail</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dropdown-content-body\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"#\"> <i class=\"ti-user\"></i> <span>Profile</span>\r\n");
      out.write("											</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<li><a href=\"#\"> <i class=\"ti-settings\"></i> <span>Setting</span>\r\n");
      out.write("											</a></li>\r\n");
      out.write("\r\n");
      out.write("											<li><a href=\"#\"> <i class=\"ti-lock\"></i> <span>Lock\r\n");
      out.write("														Screen</span>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											\r\n");
      out.write("											<li onclick=\"javascript:location.href='logout';\"><i class=\"ti-power-off\" ></i> <span >로그아웃</span>\r\n");
      out.write("										</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	 <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" .btn {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size:15pt;  \r\n");
      out.write("  background-color: navy;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding:10px 20px 10px 20px;\r\n");
      out.write("  margin:10px;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transition:all 0.2s;\r\n");
      out.write("  text-shadow:0px -2px black;\r\n");
      out.write(" }\r\n");
      out.write(" .btn:active {\r\n");
      out.write("  transform:translateY(5px);\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content-wrap\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 p-r-0 title-margin-right\">\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <div class=\"page-title\">\r\n");
      out.write("                                <h1>뉴스 /  백신 정보 <span>게시판</span></h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /# column -->\r\n");
      out.write("                    <div class=\"col-lg-4 p-l-0 title-margin-left\">\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <div class=\"page-title\">\r\n");
      out.write("                                <ol class=\"breadcrumb\">\r\n");
      out.write("                                    <li class=\"breadcrumb-item\"><a href=\"#\">Dashboard</a></li>\r\n");
      out.write("                                    <li class=\"breadcrumb-item active\">Table-Row-Select</li>\r\n");
      out.write("                                </ol>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /# column -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /# row -->\r\n");
      out.write("                <section id=\"main-content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-title\">\r\n");
      out.write("									<h4>코로나 정보</h4>\r\n");
      out.write("										<hr border=2>\r\n");
      out.write("										<a class=\"btn\" href=\"#coronainfo01\">코로나19란?</a>\r\n");
      out.write("										<a class=\"btn\" href=\"#coronainfo02\">코로나의 증상</a>\r\n");
      out.write("									  	<a class=\"btn\" href=\"#coronainfo03\">코로나의 예방법</a>\r\n");
      out.write("									  	<hr>\r\n");
      out.write("									  	<br>\r\n");
      out.write("									  	\r\n");
      out.write("									  	<h5>1. 확진자 수/격리해제 수/검사중 수/사망자 수 (실시간, 누적 모두)</h5>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"coronainfo01\">2. 코로나19란?</h5>\r\n");
      out.write("<p class=\"ta_r mgt36\">* 현재까지 알려진 정보(2021년 3월 2일 기준) </p>\r\n");
      out.write("                        <h4 class=\"s_title_1\">코로나바이러스감염증-19(COVID-19) 정보</h4>\r\n");
      out.write("						<div class=\"data_table\">\r\n");
      out.write("						  <table border=2>\r\n");
      out.write("						    <caption>\r\n");
      out.write("						      <span class=\"hdn\">코로나바이러스감염증-19 기본정보표 - 병원체, 전파 경로, 잠복기, 진단 기준, 증상, 치료, 치명률로 구성</span>\r\n");
      out.write("					        </caption>\r\n");
      out.write("						    <colgroup>\r\n");
      out.write("						      <col style=\"width:10%\" />\r\n");
      out.write("						      <col style=\"width:60%\" />\r\n");
      out.write("					        </colgroup>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\" ><center>병원체</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\" >\r\n");
      out.write("						        <li align=\"left\" >1. Severe Acute Respiratory Syndrome-Coronavirus-2(SARS-CoV-2)</li>\r\n");
      out.write("						        <li align=\"left\">2. Coronaviridae family, Betacoronavirus genus Sarbecovirus subgenus에 속함</li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\"><center>전파 경로</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\">\r\n");
      out.write("						        <li align=\"left\">1. 주된 전파경로는 감염자의 호흡기 침방울(비말)에 의한 전파</li>\r\n");
      out.write("						        <li align=\"left\">2. 사람 간에 전파되며, 대부분의 감염은 감염자가 기침, 재채기, 말하기, 노래 등을할 때 발생한 호흡기 침방울(비말)을다른사람이 밀접접촉(주로 2m 이내)하여 발생</li>\r\n");
      out.write("						        <li align=\"left\">3. 현재까지 연구결과에 의하면, 비말 이외, 표면접촉*, 공기 등을 통해서도 전파가 가능하나, 공기전파는 의료기관의에어로졸 생성 시술**, 밀폐된공간에서 장시간 호흡기 비말을 만드는환경***등 특정 환경에서 제한적으로 전파되는 것으로 알려짐\r\n");
      out.write("						          <p class=\"mgt12\">* 감염된 사람과의 직접 접촉(악수 등) 또는 매개체(오염된 물품이나 표면)를 만진 후, 손을 씻기 전 눈, 코, 입 등을 만짐으로 바이러스 전파 </p>\r\n");
      out.write("						          <p class=\"mgt8\">** 에어로졸 생성 시술: 기관지 내시경 검사, 객담 유도, 기관삽관, 심폐소생술, 개방된 객담 흡입, 흡입기 등</p>\r\n");
      out.write("						          <p class=\"mgt8\">*** 환기가 부적절하게 이루어진 노래방, 커피숍, 주점, 실내 운동시설 등에서 감염자와 같이있거나 감염자가 떠난 즉시 그 밀폐공간을 방문한 경우</p>\r\n");
      out.write("					            </li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\"><center>잠복기</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\">\r\n");
      out.write("						        <li align=\"left\">1~14일(평균 5~7일)</li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\"><center>진단 기준</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\">\r\n");
      out.write("						        <li align=\"left\">환자 : 임상양상에 관계없이 진단을 위한 검사기준에 따라 코로나19 감염이 확인된 자</li>\r\n");
      out.write("						        <li align=\"left\">진단을 위한 검사 기준\r\n");
      out.write("						          <ul>\r\n");
      out.write("						            <li align=\"left\">코로나19 유전자(PCR) 검출</li>\r\n");
      out.write("						            <li align=\"left\">바이러스 분리</li>\r\n");
      out.write("					              </ul>\r\n");
      out.write("					            </li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\"><center>증상</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\">\r\n");
      out.write("						        <li align=\"left\">주요증상 및 징후\r\n");
      out.write("						          <ul>\r\n");
      out.write("						            <li align=\"left\">- 임상 증상은 무증상, 경증, 중등증, 중증까지 다양</li>\r\n");
      out.write("						            <li align=\"left\">- 주요 증상으로는 발열(37.5℃ 이상), 기침, 호흡곤란, 오한, 근육통, 두통, 인후통, 후각·미각소실\r\n");
      out.write("						              <p>- 그 외에 피로, 식욕감소, 가래, 소화기증상(오심, 구토, 설사 등), 혼돈, 어지러움, 콧물이나 코막힘, 객혈, 흉통, 결막염, 피부 증상 등이 다양하게 나타남</p>\r\n");
      out.write("					                </li>\r\n");
      out.write("					              </ul>\r\n");
      out.write("					            </li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\"><center>치료</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\">\r\n");
      out.write("						        <li align=\"left\">- 특이치료제는 없으며 증상에 따른 해열제, 수액공급, 진해제 등 대증치료</li>\r\n");
      out.write("						        <li align=\"left\">- 호흡 곤란 시 산소를 공급하고 필요한 경우에는 기계호흡이나 체외막 산소공급 등의 처치를 시행</li>\r\n");
      out.write("						        <li align=\"left\">- 산소 치료가 필요한 환자에서 렘데시비르의 효과가 일부 확인되어 우리나라를 포함한 여러 나라에서 긴급 승인이 되었거나, 긴급 승인을 준비 중임특이적인 항바이러스제 없음</li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <th scope=\"row\"><center>치명률</center></th>\r\n");
      out.write("						      <td class=\"ta_l\"><ul class=\"s_listin_mdot mgt0\">\r\n");
      out.write("						        <li align=\"left\">전세계 치명률은 지역, 인구집단연령 구조, 감염 상태 및 기타 요인에 의해 0.1~25%로 다양함</li>\r\n");
      out.write("						        <li align=\"left\">전세계 치명률은 0.00%~1.63% (중위값 0.27%)로 보정 후 0.00~1.54%(중위값 0.23%)(Bulletin of the World Health Organization. 2021)(https://www.who.int/bulletin/volumes/99/1/20-265892/en/)</li>\r\n");
      out.write("						        </ul></td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("					      </table>\r\n");
      out.write("						</div>   \r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"coronainfo02\">3. 코로나의 증상</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li>임상 증상은 무증상, 경증, 중등증, 중증까지 다양</li>\r\n");
      out.write("	<li>주요 증상으로는 발열 (37.5℃ 이상), 기침, 호흡곤란, 오한, 근육통, 두통, 인후통, 후각/미각 손실</li>\r\n");
      out.write("	<li>그 외에 피로, 식욕감소, 가래, 소화기증상(오심, 구토, 설사 등), 혼돈, 어지러움, 콧물이나 코막힘, 객혈, 흉통,\r\n");
      out.write("	     결막염, 피부 증상 등이 다양하게 나타남</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"coronainfo03\">4. 코로나 예방법</h5>\r\n");
      out.write("<ul>\r\n");
      out.write("	<li>식약처에서 승인된 코로나 19 <a href=\"vaccinInfo.jsp#vaccineinfo01\"><u>백신</u></a></li>\r\n");
      out.write("	<li>올바른 손씻기</li>\r\n");
      out.write("	<li>기침 예절 준수</li>\r\n");
      out.write("	<li>씻지 않은 손으로 눈, 코, 입 만지지 않기</li>\r\n");
      out.write("	<li>주위환경을 자주 소독하고 환기하기</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("										\r\n");
      out.write("										\r\n");
      out.write("										\r\n");
      out.write("                                </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /# card -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /# column -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /# row -->\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("<!-- ----------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("                <!-- /# row -->\r\n");
      out.write("                <section id=\"main-content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12\">\r\n");
      out.write("                            <div id=\"extra-area-chart\"></div>\r\n");
      out.write("                            <div id=\"morris-line-chart\"></div>\r\n");
      out.write("                            <div class=\"footer\">\r\n");
      out.write("                                <p>2018 © Admin Board. -\r\n");
      out.write("                                    <a href=\"#\">example.com</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <!-- jquery vendor -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("    <!-- nano scroller -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script><script src=\"assets/js/scripts.js\"></script>\r\n");
      out.write("    <!-- scripit init-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
