/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-08-08 20:31:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.information;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;
import member.model.vo.Member;

public final class information_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1628450379201L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1628450379205L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>information</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= Favicon ================== -->\r\n");
      out.write("    <!-- Standard -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Styles -->\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

Member loginMember = (Member) session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <div\r\n");
      out.write("      class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\r\n");
      out.write("      <div class=\"nano\">\r\n");
      out.write("         <div class=\"nano-content\">\r\n");
      out.write("            <ul>\r\n");
      out.write("               <div class=\"logo\">\r\n");
      out.write("                  <a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\r\n");
      out.write("                     <span>CovLab</span></a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <li class=\"label\">Menu</li>\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li><a href=\"/semi/indexres?page=1\">홈페이지</a></li>\r\n");
      out.write("                  <li><a href=\"/semi/views/information/information.jsp\">뉴스/백신\r\n");
      out.write("                        정보</a></li>\r\n");
      out.write("\r\n");
      out.write("                  ");
if (loginMember == null) { //일반유져
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\r\n");
      out.write("                  <li><a href=\"/semi/views/member/enroll.html\">회원가입</a></li>\r\n");
      out.write("                  <li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("                  \r\n");
      out.write("                  ");
} else if (loginMember.getUserGrade().equals("A")) { //관리자
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                     <li><a class=\"sidebar-sub-toggle\">\r\n");
      out.write("                           관리 페이지 <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li><a href=\"/semi/blistadmin?page=1\">접종 후기 관리</a></li>\r\n");
      out.write("                           <li><a href=\"/semi/mlist\">회원 관리</a></li>\r\n");
      out.write("                           <li><a href=\"/semi/vcmanage\">백신 관리</a></li>\r\n");
      out.write("                        </ul></li>\r\n");
      out.write("                  ");
} else if(loginMember.getUserGrade().equals("H")){ 
      out.write("\r\n");
      out.write("                  		<li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("                  		<li><a href=\"/semi/rinfolist\">백신 접종 관리</a></li>\r\n");
      out.write("                  ");
 } else {//로그인 
      out.write("\r\n");
      out.write("                     <li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("                     <li><a href=\"/semi/uprofile?userid=");
      out.print( loginMember.getUserId());
      out.write("&user_no=");
      out.print( loginMember.getUserNo() );
      out.write("\">MY PAGE</a></li>\r\n");
      out.write("\r\n");
      out.write("                  ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\r\n");
      out.write("                        Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\r\n");
      out.write("                     <ul>\r\n");
      out.write("                        <li><a href=\"/semi/views/member/login.jsp\" onclick=\"window.open(this.href, '로그인', 'width=700, height =800 ,top=50, left=400 ,resizeable=no');return false;\">Login</a></li>\r\n");
      out.write("                        <li><a href=\"/semi/views/member/idCheck.jsp\">Enroll</a></li>\r\n");
      out.write("                        <li><a href=\"/semi/views/member/findPasswordEmail.jsp\">Forgot password</a></li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li onclick=\"javascript:location.href='/semi/logout';\"><a><i class=\"ti-close\"\r\n");
      out.write("                       ></i> Logout</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- /# sidebar -->\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("	<script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script>\r\n");
      out.write("		<script src=\"/semi/resources/js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
 
	Member loginMember1 = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 if(loginMember1 == null){ 
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"float-left\">\r\n");
      out.write("						<div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("							<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("								class=\"line\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"float-right\">\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-bell\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-email\"></i>\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<span class=\"user-avatar\" onclick=\"javascript:location.href='/semi/views/member/login.jsp'\">로그인\r\n");
      out.write("								</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"float-left\">\r\n");
      out.write("						<div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("							<span class=\"line\"></span> <span class=\"line\"></span> <span\r\n");
      out.write("								class=\"line\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"float-right\">\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-bell\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<i class=\"ti-email\"></i>\r\n");
      out.write("								<div class=\"drop-down dropdown-menu dropdown-menu-right\">\r\n");
      out.write("									<div class=\"dropdown-content-heading\">\r\n");
      out.write("										<span class=\"text-left\">2 New Messages</span> <a\r\n");
      out.write("											href=\"email.html\"> <i class=\"ti-pencil-alt pull-right\"></i>\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dropdown-content-body\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li class=\"notification-unread\"><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li class=\"notification-unread\"><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li><a href=\"#\"> <img\r\n");
      out.write("													class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("													src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("													<div class=\"notification-content\">\r\n");
      out.write("														<small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("															PM</small>\r\n");
      out.write("														<div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("														<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("															to let you ...</div>\r\n");
      out.write("													</div>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											<li class=\"text-center\"><a href=\"#\" class=\"more-link\">See\r\n");
      out.write("													All</a></li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"dropdown dib\">\r\n");
      out.write("							<div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("								<span class=\"user-avatar\">");
      out.print( loginMember1.getUserId() );
      out.write("\r\n");
      out.write("								<i class=\"ti-angle-down f-s-10\"></i>\r\n");
      out.write("								</span>\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\r\n");
      out.write("									<div class=\"dropdown-content-heading\">\r\n");
      out.write("										<span class=\"text-left\">Upgrade Now</span>\r\n");
      out.write("										<p class=\"trial-day\">30 Days Trail</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"dropdown-content-body\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li><a href=\"#\"> <i class=\"ti-user\"></i> <span>Profile</span>\r\n");
      out.write("											</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											<li><a href=\"#\"> <i class=\"ti-settings\"></i> <span>Setting</span>\r\n");
      out.write("											</a></li>\r\n");
      out.write("\r\n");
      out.write("											<li><a href=\"#\"> <i class=\"ti-lock\"></i> <span>Lock\r\n");
      out.write("														Screen</span>\r\n");
      out.write("											</a></li>\r\n");
      out.write("											\r\n");
      out.write("											<li onclick=\"javascript:location.href='/semi/logout';\" ><i class=\"ti-power-off\" ></i> <span >로그아웃</span>\r\n");
      out.write("										</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	 <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.slider {\r\n");
      out.write("  width: 1000px;\r\n");
      out.write("  height: 550px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".slide {\r\n");
      out.write("  width: 1000px;\r\n");
      out.write("  height: 550px;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  animation: fade 1.5s;\r\n");
      out.write("  display: none;\r\n");
      out.write("}\r\n");
      out.write(".imga {\r\n");
      out.write("  width: 1000px;\r\n");
      out.write("  height: 550px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".prev,\r\n");
      out.write(".next {\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  color: black;\r\n");
      out.write("  font-size: 4rem;\r\n");
      out.write("  transition: 0.6s ease;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write(".next {\r\n");
      out.write("  right: 0;\r\n");
      out.write("}\r\n");
      out.write(".prev:hover,\r\n");
      out.write(".next:hover {\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  /*rgba(190, 190, 190, 0.5)*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes fade {\r\n");
      out.write("  from {\r\n");
      out.write("    opacity: 0.4;\r\n");
      out.write("  }\r\n");
      out.write("  to {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" /* 두번째 버튼 부분 */ \r\n");
      out.write(" .btn {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size:15pt;  \r\n");
      out.write("  background-color: #1E3269;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding:10px 20px 10px 20px;\r\n");
      out.write("  margin:10px;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transition:all 0.2s;\r\n");
      out.write(" }\r\n");
      out.write(" .btn:active {\r\n");
      out.write("  transform:translateY(5px);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .btn:hover {\r\n");
      out.write(" 	background:lightgray;\r\n");
      out.write(" 	color:black;\r\n");
      out.write(" 	transition:all 0.2s;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"content-wrap\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 p-r-0 title-margin-right\">\r\n");
      out.write("                        <div class=\"page-header\">\r\n");
      out.write("                            <div class=\"page-title\">\r\n");
      out.write("                                <h1>뉴스 /  백신 정보</h1>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /# column -->\r\n");
      out.write("                   \r\n");
      out.write("                    <!-- /# column -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /# row -->\r\n");
      out.write("                <section id=\"main-content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-title\">\r\n");
      out.write("                                <!-- 1. 코로나/백신 정보 (자동 슬라이드) -->\r\n");
      out.write("                                    <!-- <h4>1. 코로나/백신/QnA</h4> -->\r\n");
      out.write("<!-- 2. 코로나/ 백신 정보로 넘어가는 버튼 -->\r\n");
      out.write(" <h5>**메뉴 이동**</h5> \r\n");
      out.write("<a class=\"btn\" href=\"coronaInfo.jsp\">코로나 정보</a>\r\n");
      out.write("<a class=\"btn\" href=\"vaccinInfo.jsp\">백신/예방접종 정보</a>\r\n");
      out.write("<a class=\"btn\" href=\"qna.jsp\">QnA</a>\r\n");
      out.write("<!-- <a class=\"btn\" href=\"test2.jsp\">test2</a> -->\r\n");
      out.write("<hr>\r\n");
      out.write("<!-- 자동배너 (이미지 넣고, 수정해야함) -->\r\n");
      out.write("<br>\r\n");
      out.write("  <div class=\"slider\" >\r\n");
      out.write("      <!-- <div class=\"slide\" style=\"background-image: url(../../resources/images/info_num.jpg);\"></div>   -->\r\n");
      out.write("      <div class=\"slide\" style=\"background-image: url(../../resources/images/info_num2.jpeg);\">\r\n");
      out.write("      	<a href=\"coronaInfo.jsp\"><img src=\"../../resources/images/info_num2.jpeg\" class=\"imga\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"slide\" style=\"background-image: url(../../resources/images/info_vac.gif);\">\r\n");
      out.write("      	<a href=\"vaccinInfo.jsp\"><img src=\"../../resources/images/info_vac.gif\" class=\"imga\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"slide\" style=\"background-image: url(../../resources/images/info_qna2.jpg);\">\r\n");
      out.write("      	<a href=\"qna.jsp\"><img src=\"../../resources/images/info_qna2.jpg\" class=\"imga\"></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a class=\"prev\" onclick=\"button_click(-1)\">&#10094</a>\r\n");
      out.write("      <a class=\"next\" onclick=\"button_click(1)\">&#10095</a>\r\n");
      out.write("    </div>\r\n");
      out.write("<br>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!-- 3. 실시간 뉴스 -->\r\n");
      out.write("<h5>**뉴스 & 이슈**</h5><br>\r\n");
      out.write("<a href=\"https://www.yna.co.kr/view/AKR20210805071200002?input=1195m\" class=\"new\"><u>코로나로 힘든 대형마트 입점업체, 임대료 감액 요청할 수 있다</u></a><br>\r\n");
      out.write("<a href=\"https://biz.chosun.com/it-science/ict/2021/08/05/MTTS3BYF7JE47KXPKWH4LA6WTQ/?utm_source=naver&utm_medium=original&utm_campaign=biz\">\r\n");
      out.write("<u>네이버·카카오 앱으로 18~49세 코로나 백신 예약</u></a><br>\r\n");
      out.write("<a href=\"https://www.news1.kr/articles/?4394395\"><u>두번째 코로나 수능, 백신 맞아도 마스크…점심때만 3면 칸막이</u></a><br>\r\n");
      out.write("<a href=\"https://newsis.com/view/?id=NISX20210805_0001538550&cID=13102&pID=13100\"><u>코로나19, 실내 공간 감염 위험 4배 높다</u></a><br>\r\n");
      out.write("<a href=\"https://www.hani.co.kr/arti/society/health/1006519.html\"><u>코로나19 신규 확진자 1776명…30일째 1천명대</u></a><br>\r\n");
      out.write("<a href=\"https://www.yna.co.kr/view/AKR20210804130100017?input=1195m\"><u>국내 부모 64.2% \"우리 아이 코로나 백신 맞히겠다\"</u></a><br>\r\n");
      out.write("<a href=\"https://www.korea.kr/news/policyNewsView.do?newsId=148888328\"><u>‘글로벌 백신 허브화 TF’ 출범…“국내 백신 생산역량 강화”</u></a>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("  \r\n");
      out.write("                                </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /# card -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /# column -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /# row -->\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("<!-- ---------------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- jquery vendor -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script><script src=\"assets/js/scripts.js\"></script>\r\n");
      out.write("    <!-- scripit init-->\r\n");
      out.write("\r\n");
      out.write("<!-- 자동배너 부분의 스크립트 -->\r\n");
      out.write(" <script>\r\n");
      out.write("let currSlide = 1;\r\n");
      out.write("showSlide(currSlide);\r\n");
      out.write("\r\n");
      out.write("function button_click(num){\r\n");
      out.write("  showSlide((currSlide += num));\r\n");
      out.write("}\r\n");
      out.write("function showSlide(num){\r\n");
      out.write("  const slides = document.querySelectorAll(\".slide\");\r\n");
      out.write("  if(num>slides.length){\r\n");
      out.write("    currSlide =1;\r\n");
      out.write("  }if(num<1){\r\n");
      out.write("    currSlide = slides.length;\r\n");
      out.write("  }\r\n");
      out.write("  for(let i=0; i<slides.length; i++){\r\n");
      out.write("    slides[i].style.display=\"none\";\r\n");
      out.write("  }slides[currSlide -1].style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
