/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-27 07:24:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.information;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1627108527600L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1627095786638L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("@@ -0,0 +1,205 @@\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>QnA</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= Favicon ================== -->\r\n");
      out.write("    <!-- Standard -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Styles -->\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	//Member loginMember = (Member)session.getAttribute("loginMember");

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\r\n");
      out.write("		<div class=\"nano\">\r\n");
      out.write("			<div class=\"nano-content\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<div class=\"logo\">\r\n");
      out.write("						<a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\r\n");
      out.write("							<span>CovLab</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<li class=\"label\">Menu</li>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">백신 예약</a></li>\r\n");
      out.write("						<li><a href=\"/semi/views/information/information.jsp\">뉴스/백신 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("						");
 if(true){ //로그인
      out.write(" <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\r\n");
      out.write("						<a href=\"/semi/views/member/idcheck.jsp\">회원가입</a>\r\n");
      out.write("							\r\n");
      out.write("						");
 }else{  //로그인 아닐시 
      out.write("\r\n");
      out.write("							<a href=\"/semi/index.jsp\">MY PAGE</a>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						");
 if(true){ //관리자 
      out.write("\r\n");
      out.write("							<li><a href=\"/semi/blistadmin?page=1\">접종 후기 관리</a></li>\r\n");
      out.write("						");
 } else { 
      out.write("\r\n");
      out.write("							<li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">MY PAGE</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\r\n");
      out.write("							Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"page-login.html\">Login</a></li>\r\n");
      out.write("							<li><a href=\"page-register.html\">Register</a></li>\r\n");
      out.write("							<li><a href=\"page-reset-password.html\">Forgot password</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"../documentation/index.html\"><i\r\n");
      out.write("							class=\"ti-file\"></i> Documentation</a></li>\r\n");
      out.write("					<li><a><i class=\"ti-close\"></i> Logout</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /# sidebar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"float-left\">\r\n");
      out.write("                        <div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"float-right\">\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"ti-bell\"></i>\r\n");
      out.write("                                \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"ti-email\"></i>\r\n");
      out.write("                                <div class=\"drop-down dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\r\n");
      out.write("                                        <span class=\"text-left\">2 New Messages</span>\r\n");
      out.write("                                        <a href=\"email.html\">\r\n");
      out.write("                                            <i class=\"ti-pencil-alt pull-right\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"dropdown-content-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li class=\"notification-unread\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"notification-unread\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"text-center\">\r\n");
      out.write("                                                <a href=\"#\" class=\"more-link\">See All</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <span class=\"user-avatar\">John\r\n");
      out.write("                                    <i class=\"ti-angle-down f-s-10\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\r\n");
      out.write("                                        <span class=\"text-left\">Upgrade Now</span>\r\n");
      out.write("                                        <p class=\"trial-day\">30 Days Trail</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"dropdown-content-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-user\"></i>\r\n");
      out.write("                                                    <span>Profile</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-settings\"></i>\r\n");
      out.write("                                                    <span>Setting</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-lock\"></i>\r\n");
      out.write("                                                    <span>Lock Screen</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-power-off\"></i>\r\n");
      out.write("                                                    <span>Logout</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" .btn {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size:15pt;  \r\n");
      out.write("  background-color: navy;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding:10px 20px 10px 20px;\r\n");
      out.write("  margin:10px;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transition:all 0.2s;\r\n");
      out.write("  text-shadow:0px -2px black;\r\n");
      out.write(" }\r\n");
      out.write(" .btn:active {\r\n");
      out.write("  transform:translateY(5px);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" dl.faq button {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin-top: 1em;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  font-size: 110%;\r\n");
      out.write("  border: thin solid transparent;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  padding-left: 0.125em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl dd {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin-left: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq .desc {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0.5em;\r\n");
      out.write("  font-size: 110%;\r\n");
      out.write("  display: none;\r\n");
      out.write("  background-color: #fffedb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq button:hover,\r\n");
      out.write("dl.faq button:focus {\r\n");
      out.write("  background-color: #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq button:focus {\r\n");
      out.write("  border-color: #630;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq button:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq button:active {\r\n");
      out.write("  background-color: #bbb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq button[aria-expanded=\"false\"]::before {\r\n");
      out.write("  content: url('../images/right-arrow-brown.png');\r\n");
      out.write("  padding-right: 0.35em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl.faq button[aria-expanded=\"true\"]::before {\r\n");
      out.write("  content: url('../images/down-arrow-brown.png');\r\n");
      out.write("  padding-right: 0.35em;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h4>QnA</h4>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<a class=\"btn\" href=\"#qna01\">코로나란?</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna02\">코로나의 증상/검사</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna03\">임신과 출산</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna04\">치료 및 예방</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna05\">접촉자 및 확진환자</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna06\">격리 및 격리해제</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna07\">백신 관련</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna08\">백신의 안전성과 이상반응</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna09\">코로나19 예방접종 관련 피해보상</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna10\">인과성 불충분한 중증 환자 의료비 지원사업</a>\r\n");
      out.write("<a class=\"btn\" href=\"#qna11\">기타</a>\r\n");
      out.write("<hr>\r\n");
      out.write("<!-- 윗부분은 목록을 만들고 a 태그로 각 번호의 목록으로 이동하게 만듬 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 각 목록의 내용을 번호를 붙여서 작성 -->\r\n");
      out.write("<h5 id=\"qna01\">1. 코로나란?</h5>\r\n");
      out.write("<dl class=\"faq\">\r\n");
      out.write("  <dt>\r\n");
      out.write("    <button aria-expanded=\"false\" aria-controls=\"faq1_desc\">\r\n");
      out.write("      코로나 바이러스 감염증-19는 어떤 질병인가요?\r\n");
      out.write("    </button>\r\n");
      out.write("  </dt>\r\n");
      out.write("  <dd>\r\n");
      out.write("    <p id=\"faq1_desc\" class=\"desc\">\r\n");
      out.write("    	1. 코로나 바이러스 감염증-19(코로나19)는 과거에 발견되지 않았던 새로운 코로나 바이러스인 SARS-CoV-2에 의해 발생하는\r\n");
      out.write("    	호흡기 감염병으로, 이 바이러스에 감염되면 무증상부터 중증에 이르기까지 다양한 임상증상이 나타날 수 있습니다.  <br>\r\n");
      out.write("    	2. 이 새로운 바이러스와 질병은 2019년 12월 중국 우한에서 처음 보고되었고, 현재 전 세계에 확산되었습니다.\r\n");
      out.write("    </p>\r\n");
      out.write("  </dd>\r\n");
      out.write("   <dt>\r\n");
      out.write("    <button aria-expanded=\"false\" aria-controls=\"faq2_desc\">\r\n");
      out.write("      코로나 바이러스는 어떤 바이러스인가요?\r\n");
      out.write("    </button>\r\n");
      out.write("  </dt>\r\n");
      out.write("  <dd>\r\n");
      out.write("    <p id=\"faq2_desc\" class=\"desc\">\r\n");
      out.write("    	1. 코로나 바이러스는 동물 및 사람에게 전파될 수 있는 바이러스로 그 중 사람에게 전파가능 함 사람 코로나 바이러스는 기존에\r\n");
      out.write("    	6종이 알려져 있습니다.<br>\r\n");
      out.write("    	2. 이 중 4종은 감기와 같은 질병을 일으키는 바이러스이며, 나머지 2종은 각각 MERS-CoV와 SARS-CoV로 알려져있습니다.<br>\r\n");
      out.write("    	3. 이번 유행의 원인 바이러스는 코로나바이러스(SARS-CoV-2)로 공개된 염기서열 분석을 통해 코로나 19 바이러스가 박쥐유래\r\n");
      out.write("    	사스 유사 바이러스와 89.1% 일치하는 것을 확인하였습니다.\r\n");
      out.write("    </p>\r\n");
      out.write("  </dd>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </dl>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h5 id=\"qna02\">2. 코로나19 예방접종 사업</h5>\r\n");
      out.write("<p>예방접종 하면 좋겠죠.. 건강할거에요.. 그럴거에요...</p>\r\n");
      out.write("<p>예방접종 하면 좋겠죠.. 건강할거에요.. 그럴거에요...</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"qna03\">3. 백신 관련</h5>\r\n");
      out.write("<p>백신이 점점 업그레이드 좀 됐으면 좋겠어요.</p>\r\n");
      out.write("<p>백신이 점점 업그레이드 좀 됐으면 좋겠어요.</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"qna04\">4. 백신의 안전성과 이상반응</h5>\r\n");
      out.write("<p>백신은 안전하지 않은것 같지만.. 괜찮아지길 바래요.. 이상있음 병원가야 합니다...</p>\r\n");
      out.write("<p>백신은 안전하지 않은것 같지만.. 괜찮아지길 바래요.. 이상있음 병원가야 합니다...</p>\r\n");
      out.write("<p>백신은 안전하지 않은것 같지만.. 괜찮아지길 바래요.. 이상있음 병원가야 합니다...</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"qna05\">5. 코로나19 예방접종 관련 피해보상</h5>\r\n");
      out.write("<p>코로나로 피해를 받으셨으면 보상을 받으세요. 보상해줍니다.</p>\r\n");
      out.write("<p>코로나로 피해를 받으셨으면 보상을 받으세요. 보상해줍니다.</p>\r\n");
      out.write("<p>코로나로 피해를 받으셨으면 보상을 받으세요. 보상해줍니다.</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"qna06\">6. 인과성 불충분한 중증 환자 의료비 지원사업</h5>\r\n");
      out.write("<p>인과성 자료가 부족해도 보상 받을 수 있습니다.</p>\r\n");
      out.write("<p>인과성 자료가 부족해도 보상 받을 수 있습니다.</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"qna07\">7. 75세 이상 어르신 및 노인시설 예방접종</h5>\r\n");
      out.write("<p>어르신들께서 건강하시길 바랍니다.</p>\r\n");
      out.write("<p>어르신들께서 건강하시길 바랍니다.</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"qna08\">8. 시스템및 예방접종 기록</h5>\r\n");
      out.write("<p>예방접종 하면 기록이 생깁니다.</p>\r\n");
      out.write("<p>예방접종 하면 기록이 생깁니다.</p>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("                <!-- /# row -->\r\n");
      out.write("                <section id=\"main-content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12\">\r\n");
      out.write("                            <div id=\"extra-area-chart\"></div>\r\n");
      out.write("                            <div id=\"morris-line-chart\"></div>\r\n");
      out.write("                            <div class=\"footer\">\r\n");
      out.write("                                <p>2018 © Admin Board. -\r\n");
      out.write("                                    <a href=\"#\">example.com</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <!-- jquery vendor -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("    <!-- nano scroller -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script><script src=\"assets/js/scripts.js\"></script>\r\n");
      out.write("    <!-- scripit init-->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/*\r\n");
      out.write("*   This content is licensed according to the W3C Software License at\r\n");
      out.write("*   https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document\r\n");
      out.write("*\r\n");
      out.write("*   File:   ButtonExpand.js\r\n");
      out.write("*\r\n");
      out.write("*   Desc:   Checkbox widget that implements ARIA Authoring Practices\r\n");
      out.write("*           for a menu of links\r\n");
      out.write("*/\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write("*   @constructor ButtonExpand\r\n");
      out.write("*\r\n");
      out.write("*\r\n");
      out.write("*/\r\n");
      out.write("var ButtonExpand = function (domNode) {\r\n");
      out.write("\r\n");
      out.write("  this.domNode = domNode;\r\n");
      out.write("\r\n");
      out.write("  this.keyCode = Object.freeze({\r\n");
      out.write("    'RETURN': 13\r\n");
      out.write("  });\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.init = function () {\r\n");
      out.write("\r\n");
      out.write("  this.controlledNode = false;\r\n");
      out.write("\r\n");
      out.write("  var id = this.domNode.getAttribute('aria-controls');\r\n");
      out.write("\r\n");
      out.write("  if (id) {\r\n");
      out.write("    this.controlledNode = document.getElementById(id);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  this.domNode.setAttribute('aria-expanded', 'false');\r\n");
      out.write("  this.hideContent();\r\n");
      out.write("\r\n");
      out.write("  this.domNode.addEventListener('keydown',    this.handleKeydown.bind(this));\r\n");
      out.write("  this.domNode.addEventListener('click',      this.handleClick.bind(this));\r\n");
      out.write("  this.domNode.addEventListener('focus',      this.handleFocus.bind(this));\r\n");
      out.write("  this.domNode.addEventListener('blur',       this.handleBlur.bind(this));\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.showContent = function () {\r\n");
      out.write("\r\n");
      out.write("  if (this.controlledNode) {\r\n");
      out.write("    this.controlledNode.style.display = 'block';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.hideContent = function () {\r\n");
      out.write("\r\n");
      out.write("  if (this.controlledNode) {\r\n");
      out.write("    this.controlledNode.style.display = 'none';\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.toggleExpand = function () {\r\n");
      out.write("\r\n");
      out.write("  if (this.domNode.getAttribute('aria-expanded') === 'true') {\r\n");
      out.write("    this.domNode.setAttribute('aria-expanded', 'false');\r\n");
      out.write("    this.hideContent();\r\n");
      out.write("  }\r\n");
      out.write("  else {\r\n");
      out.write("    this.domNode.setAttribute('aria-expanded', 'true');\r\n");
      out.write("    this.showContent();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("/* EVENT HANDLERS */\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.handleKeydown = function (event) {\r\n");
      out.write("\r\n");
      out.write("  console.log('[keydown]');\r\n");
      out.write("\r\n");
      out.write("  switch (event.keyCode) {\r\n");
      out.write("\r\n");
      out.write("    case this.keyCode.RETURN:\r\n");
      out.write("\r\n");
      out.write("      this.toggleExpand();\r\n");
      out.write("\r\n");
      out.write("      event.stopPropagation();\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("      break;\r\n");
      out.write("\r\n");
      out.write("    default:\r\n");
      out.write("      break;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.handleClick = function (event) {\r\n");
      out.write("  this.toggleExpand();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.handleFocus = function (event) {\r\n");
      out.write("  this.domNode.classList.add('focus');\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("ButtonExpand.prototype.handleBlur = function (event) {\r\n");
      out.write("  this.domNode.classList.remove('focus');\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("/* Initialize Hide/Show Buttons */\r\n");
      out.write("\r\n");
      out.write("window.addEventListener('load', function (event) {\r\n");
      out.write("\r\n");
      out.write("  var buttons =  document.querySelectorAll('button[aria-expanded][aria-controls]');\r\n");
      out.write("\r\n");
      out.write("  for (var i = 0; i < buttons.length; i++) {\r\n");
      out.write("    var be = new ButtonExpand(buttons[i]);\r\n");
      out.write("    be.init();\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("}, false);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
