/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-27 06:12:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.information;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnatest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1627108527600L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1627095786638L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>QnA</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= Favicon ================== -->\r\n");
      out.write("    <!-- Standard -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Styles -->\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	//Member loginMember = (Member)session.getAttribute("loginMember");

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\r\n");
      out.write("		<div class=\"nano\">\r\n");
      out.write("			<div class=\"nano-content\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<div class=\"logo\">\r\n");
      out.write("						<a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\r\n");
      out.write("							<span>CovLab</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<li class=\"label\">Menu</li>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">백신 예약</a></li>\r\n");
      out.write("						<li><a href=\"/semi/views/information/information.jsp\">뉴스/백신 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("						");
 if(true){ //로그인
      out.write(" <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\r\n");
      out.write("						<a href=\"/semi/views/member/idcheck.jsp\">회원가입</a>\r\n");
      out.write("							\r\n");
      out.write("						");
 }else{  //로그인 아닐시 
      out.write("\r\n");
      out.write("							<a href=\"/semi/index.jsp\">MY PAGE</a>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						");
 if(true){ //관리자 
      out.write("\r\n");
      out.write("							<li><a href=\"/semi/blistadmin?page=1\">접종 후기 관리</a></li>\r\n");
      out.write("						");
 } else { 
      out.write("\r\n");
      out.write("							<li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">MY PAGE</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\r\n");
      out.write("							Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"page-login.html\">Login</a></li>\r\n");
      out.write("							<li><a href=\"page-register.html\">Register</a></li>\r\n");
      out.write("							<li><a href=\"page-reset-password.html\">Forgot password</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"../documentation/index.html\"><i\r\n");
      out.write("							class=\"ti-file\"></i> Documentation</a></li>\r\n");
      out.write("					<li><a><i class=\"ti-close\"></i> Logout</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /# sidebar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"float-left\">\r\n");
      out.write("                        <div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"float-right\">\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"ti-bell\"></i>\r\n");
      out.write("                                \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"ti-email\"></i>\r\n");
      out.write("                                <div class=\"drop-down dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\r\n");
      out.write("                                        <span class=\"text-left\">2 New Messages</span>\r\n");
      out.write("                                        <a href=\"email.html\">\r\n");
      out.write("                                            <i class=\"ti-pencil-alt pull-right\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"dropdown-content-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li class=\"notification-unread\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"notification-unread\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"text-center\">\r\n");
      out.write("                                                <a href=\"#\" class=\"more-link\">See All</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <span class=\"user-avatar\">John\r\n");
      out.write("                                    <i class=\"ti-angle-down f-s-10\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\r\n");
      out.write("                                        <span class=\"text-left\">Upgrade Now</span>\r\n");
      out.write("                                        <p class=\"trial-day\">30 Days Trail</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"dropdown-content-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-user\"></i>\r\n");
      out.write("                                                    <span>Profile</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-settings\"></i>\r\n");
      out.write("                                                    <span>Setting</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-lock\"></i>\r\n");
      out.write("                                                    <span>Lock Screen</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-power-off\"></i>\r\n");
      out.write("                                                    <span>Logout</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/javaScript\" language=\"javascript\">\r\n");
      out.write("function showView(seq){\r\n");
      out.write("\r\n");
      out.write("	if ($('#'+seq+'p').html() != \"\" ){\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : 'post',\r\n");
      out.write("		dataType : 'html',\r\n");
      out.write("		url : '/ncvCmBoardView.do',\r\n");
      out.write("		data : {'seq':seq},\r\n");
      out.write("		success : function(html){\r\n");
      out.write("			\r\n");
      out.write("			var html1 = decodeURIComponent(html);\r\n");
      out.write("	\r\n");
      out.write("			html1 = html1.replace(/\\+/g, \" \");\r\n");
      out.write("		\r\n");
      out.write("			$('#'+seq+'p').html(html1);\r\n");
      out.write("			//$('#'+seq).append(\"<p id='\"+seq+\"p'>\"+html1+\"</p>\");\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<a class=\"btn\" href=\"#qna01\">코로나란?</a>\r\n");
      out.write("\r\n");
      out.write("<div class=\"faq_list\">\r\n");
      out.write("						<ul>\r\n");
      out.write("						\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3473');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >코로나바이러스감염증-19는 어떤 질병인가요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3473\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3473\" >\r\n");
      out.write("			                              	<p id=\"3473p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3474');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >코로나바이러스는 어떤 바이러스인가요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3474\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3474\" >\r\n");
      out.write("			                              	<p id=\"3474p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3475');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >코로나바이러스감염증-19, 코로나19(COVID-19)의 이름은 어떻게 지어졌나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3475\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3475\" >\r\n");
      out.write("			                              	<p id=\"3475p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3476');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >코로나19의 바이러스는 어디에서 유래했나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3476\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3476\" >\r\n");
      out.write("			                              	<p id=\"3476p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3477');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >코로나19는 어떻게 전염되나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3477\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3477\" >\r\n");
      out.write("			                              	<p id=\"3477p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3478');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >지역사회 감염이 무엇인가요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3478\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3478\" >\r\n");
      out.write("			                              	<p id=\"3478p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3479');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >코로나19 환자의 대변이나 체액으로도 전염이 가능한가요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3479\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3479\" >\r\n");
      out.write("			                              	<p id=\"3479p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3480');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >음식을 통해 코로나19가 전염될 수 있나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3480\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3480\" >\r\n");
      out.write("			                              	<p id=\"3480p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3481');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >날씨가 따뜻해지면 코로나19 전파를 막을 수 있나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3481\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3481\" >\r\n");
      out.write("			                              	<p id=\"3481p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('3482');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >모기나 진드기 같은 곤충이 코로나19를 전파시킬 수 있나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=3482\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"3482\" >\r\n");
      out.write("			                              	<p id=\"3482p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("									\r\n");
      out.write("								<li>\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"fl_q_n lt_l\" onClick=\"showView('5541');\">\r\n");
      out.write("										<span class=\"ico_q_n\" >Q</span>\r\n");
      out.write("										<span class=\"fl_ttl\" >카페 등의 다중이용시설 및 가정에서 냉난방기 가동시, 환기는 얼마나 자주 해야 하나요?</span>\r\n");
      out.write("										<i></i>\r\n");
      out.write("									</a>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"fl_a_n lt_c\">\r\n");
      out.write("										<!--글내용-->\r\n");
      out.write("										<a target=\"_blank\" href=\"/shBoardView.do?brdId=3&brdGubun=38&ncvContSeq=5541\"  class=\"a_sha\" title=\"공유하기\">공유하기</a>\r\n");
      out.write("										<span class=\"ico_a_n\">A</span>\r\n");
      out.write("										<div class=\"s_descript mgt0\"  id=\"5541\" >\r\n");
      out.write("			                              	<p id=\"5541p\" ></p>\r\n");
      out.write("										</div>\r\n");
      out.write("									<!--글내용-->\r\n");
      out.write("									<!--첨부파일-->\r\n");
      out.write("									\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								</li>\r\n");
      out.write("	\r\n");
      out.write("						\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
