/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-26 09:10:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.information;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vaccinInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/information/../common/sidebar.jsp", Long.valueOf(1627108527600L));
    _jspx_dependants.put("/views/information/../common/topbar.jsp", Long.valueOf(1627095786638L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("@@ -0,0 +1,128 @@\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>VaccineInfo</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= Favicon ================== -->\r\n");
      out.write("    <!-- Standard -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://placehold.it/64.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"http://placehold.it/144.png/000/fff\">\r\n");
      out.write("    <!-- Retina iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"http://placehold.it/114.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPad Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"http://placehold.it/72.png/000/fff\">\r\n");
      out.write("    <!-- Standard iPhone Touch Icon-->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"http://placehold.it/57.png/000/fff\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Styles -->\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/themify-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/menubar/sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/lib/helper.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/semi/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	//로그인 확인을 위해서 내장된 session 객체를 이용
	//Member loginMember = (Member)session.getAttribute("loginMember");

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures\">\r\n");
      out.write("		<div class=\"nano\">\r\n");
      out.write("			<div class=\"nano-content\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<div class=\"logo\">\r\n");
      out.write("						<a href=\"index1.html\"> <!-- <img src=\"assets/images/logo.png\" alt=\"\" /> -->\r\n");
      out.write("							<span>CovLab</span></a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<li class=\"label\">Menu</li>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">백신 예약</a></li>\r\n");
      out.write("						<li><a href=\"/semi/views/information/information.jsp\">뉴스/백신 정보</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li>\r\n");
      out.write("						");
 if(true){ //로그인
      out.write(" <!--회원가입 창 만들었는데 아니다 싶으면 지워주세여  -->\r\n");
      out.write("						<a href=\"/semi/views/member/idcheck.jsp\">회원가입</a>\r\n");
      out.write("							\r\n");
      out.write("						");
 }else{  //로그인 아닐시 
      out.write("\r\n");
      out.write("							<a href=\"/semi/index.jsp\">MY PAGE</a>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("						");
 if(true){ //관리자 
      out.write("\r\n");
      out.write("							<li><a href=\"/semi/blistadmin?page=1\">접종 후기 관리</a></li>\r\n");
      out.write("						");
 } else { 
      out.write("\r\n");
      out.write("							<li><a href=\"/semi/blist?page=1\">접종 후기</a></li>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("						<li><a href=\"/semi/index.jsp\">MY PAGE</a></li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li><a class=\"sidebar-sub-toggle\"><i class=\"ti-target\"></i>\r\n");
      out.write("							Pages <span class=\"sidebar-collapse-icon ti-angle-down\"></span></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"page-login.html\">Login</a></li>\r\n");
      out.write("							<li><a href=\"page-register.html\">Register</a></li>\r\n");
      out.write("							<li><a href=\"page-reset-password.html\">Forgot password</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"../documentation/index.html\"><i\r\n");
      out.write("							class=\"ti-file\"></i> Documentation</a></li>\r\n");
      out.write("					<li><a><i class=\"ti-close\"></i> Logout</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /# sidebar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"float-left\">\r\n");
      out.write("                        <div class=\"hamburger sidebar-toggle\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"float-right\">\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"ti-bell\"></i>\r\n");
      out.write("                                \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"ti-email\"></i>\r\n");
      out.write("                                <div class=\"drop-down dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\r\n");
      out.write("                                        <span class=\"text-left\">2 New Messages</span>\r\n");
      out.write("                                        <a href=\"email.html\">\r\n");
      out.write("                                            <i class=\"ti-pencil-alt pull-right\"></i>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"dropdown-content-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li class=\"notification-unread\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/1.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"notification-unread\">\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/3.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Michael Qin</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <img class=\"pull-left m-r-10 avatar-img\"\r\n");
      out.write("                                                        src=\"/semi/resources/images/avatar/2.jpg\" alt=\"\" />\r\n");
      out.write("                                                    <div class=\"notification-content\">\r\n");
      out.write("                                                        <small class=\"notification-timestamp pull-right\">02:34\r\n");
      out.write("                                                            PM</small>\r\n");
      out.write("                                                        <div class=\"notification-heading\">Mr. John</div>\r\n");
      out.write("                                                        <div class=\"notification-text\">Hi Teddy, Just wanted to let you\r\n");
      out.write("                                                            ...</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"text-center\">\r\n");
      out.write("                                                <a href=\"#\" class=\"more-link\">See All</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"dropdown dib\">\r\n");
      out.write("                            <div class=\"header-icon\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <span class=\"user-avatar\">John\r\n");
      out.write("                                    <i class=\"ti-angle-down f-s-10\"></i>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"drop-down dropdown-profile dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                                    <div class=\"dropdown-content-heading\">\r\n");
      out.write("                                        <span class=\"text-left\">Upgrade Now</span>\r\n");
      out.write("                                        <p class=\"trial-day\">30 Days Trail</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"dropdown-content-body\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-user\"></i>\r\n");
      out.write("                                                    <span>Profile</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-settings\"></i>\r\n");
      out.write("                                                    <span>Setting</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-lock\"></i>\r\n");
      out.write("                                                    <span>Lock Screen</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li>\r\n");
      out.write("                                                <a href=\"#\">\r\n");
      out.write("                                                    <i class=\"ti-power-off\"></i>\r\n");
      out.write("                                                    <span>Logout</span>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(" .btn {\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size:15pt;  \r\n");
      out.write("  background-color: navy;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding:10px 20px 10px 20px;\r\n");
      out.write("  margin:10px;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transition:all 0.2s;\r\n");
      out.write("  text-shadow:0px -2px black;\r\n");
      out.write(" }\r\n");
      out.write(" .btn:active {\r\n");
      out.write("  transform:translateY(5px);\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h4>백신/예방접종 정보</h4>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<a class=\"btn\" href=\"#vaccineinfo01\">우리나라에 들어오는 백신</a>\r\n");
      out.write("<a class=\"btn\" href=\"#vaccineinfo02\">예방접종 이후 증상</a>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<!-- 윗부분은 목록을 만들고 a 태그로 각 번호의 목록으로 이동하게 만듬 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 각 목록의 내용을 번호를 붙여서 작성 -->\r\n");
      out.write("<h5>*백신 접종 현황 (1차 접종 / 백신 접종 완료)*</h5>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"vaccineinfo01\">*우리나라에 들어오는 백신*</h5>\r\n");
      out.write("<table border=\"1\" height=\"60%\" width=\"80%\">\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td>백신이름</td>\r\n");
      out.write("		<td>아스트라제네카</td>\r\n");
      out.write("		<td>화이자</td>\r\n");
      out.write("		<td>모더나</td>\r\n");
      out.write("		<td>얀센</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\">개발국</td>\r\n");
      out.write("		<td align=\"left\">영국</td>\r\n");
      out.write("		<td align=\"left\">미국/독일</td>\r\n");
      out.write("		<td align=\"left\">미국</td>\r\n");
      out.write("		<td align=\"left\">미국</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td align=\"center\">방식</td>\r\n");
      out.write("		<td align=\"left\">독감 바이러스 전달체로 활용</td>\r\n");
      out.write("		<td align=\"left\">전령 RNA</td>\r\n");
      out.write("		<td align=\"left\">전령 RNA</td>\r\n");
      out.write("		<td align=\"left\">아데노 바이러스 전달체로 활용</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\">투여대상</td>\r\n");
      out.write("		<td align=\"left\">18세 이상</td>\r\n");
      out.write("		<td align=\"left\">16세 이상</td>\r\n");
      out.write("		<td align=\"left\">18세 이상</td>\r\n");
      out.write("		<td align=\"left\">미정</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td align=\"center\">예방효과</td>\r\n");
      out.write("		<td align=\"left\"><font color=\"red\">62~70%</font><br>\r\n");
      out.write("		       영국,브라질 3상 62%, <br>저용량/표준 용량 70%</td>\r\n");
      out.write("		<td align=\"left\"><font color=\"red\">95%</font><br>연령, 인종, 민족적 차이 없이 일관</td>\r\n");
      out.write("		<td align=\"left\"><font color=\"red\">94.1%</font><br>최소 3개월 항체 유지</td>\r\n");
      out.write("		<td align=\"left\"><font color=\"red\">평균 66%</font><br>미국 72%, 남아공 57% <br> 라틴아메리카 66%</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td align=\"center\">접종횟수</td>\r\n");
      out.write("		<td align=\"left\">2회</td>\r\n");
      out.write("		<td align=\"left\">2회</td>\r\n");
      out.write("		<td align=\"left\">2회</td>\r\n");
      out.write("		<td align=\"left\">1회</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td align=\"center\">보관유통</td>\r\n");
      out.write("		<td align=\"left\">6개월동안<br> 냉장상태(2~8℃) 보관, 운반, 취급 가능</td>\r\n");
      out.write("		<td align=\"left\">-70℃ 이하의 초저온 '콜드체인' 통해 유통<br>\r\n");
      out.write("								  -80℃~-60℃ 6개월<br>2℃~8℃ 5일<br>25℃ 2시간 보관가능</td>\r\n");
      out.write("		<td align=\"left\">-25℃~-15℃ 6개월 <br> 2~8℃ 최대 30일간 안정적인 상태유지 <br> 8℃~25℃ 12시간</td>\r\n");
      out.write("		<td align=\"left\">2~8℃에서 최소 3개월 <br>-20℃에서 2년 보관</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write(" <p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 id=\"vaccineinfo02\">*예방접종 이후*</h5>\r\n");
      out.write("<div>\r\n");
      out.write("	<h4>1. 예방접종 이후 주의 사항</h4>\r\n");
      out.write("	<img src=\"../../resources/images/vaccination01.jpg\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><font size=\"4\">접종받은 기관에서 15~30분 가량 머무르며 즉각적으로 나타날 수 있는 이상반응의 발생여부를 관찰합니다.</font></li>\r\n");
      out.write("		<li><font size=\"4\">예방접종 이후 최소 3일동안은 몸 상태를 주의 깊게 살펴야 합니다.</font></li>\r\n");
      out.write("		<li><font size=\"4\">예방접종을 한 당일에는 간단한 샤워는 가능하지만 반식욕, 사우나, 찜질방, 수영 등은 피하고 충분한 휴식을 취합니다.</font></li>\r\n");
      out.write("		<li><font size=\"4\">접종 1~2일 후에는 금주하고, 접종 부위는 청결하게 유지하며 긁지 않도록 합니다.</font></li>\r\n");
      out.write("		<li><font size=\"4\">만약 예방접종 후 고열, 두드러기, 호흡곤란, 입술 또는 입안의 부종 등 심한 알레르기 반응 등 평소와 다른 증상이\r\n");
      out.write("		 있는 경우에는 즉시 접종기관이나 가까운 외료기관을 방문하여 진료를 받아야 합니다.</font></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<hr width=\"40%\" align=\"left\">\r\n");
      out.write("<div>\r\n");
      out.write("	<h4>2. 예방접종 이후 이상반응</h4>\r\n");
      out.write("	<img src=\"../../resources/images/vaccination02.png\">\r\n");
      out.write("	<ul>	\r\n");
      out.write("		<li><font size=\"4\">발열증상		\r\n");
      out.write("			<p>접종 후 39℃미만의 발열증상은 정상적인 면역반응일 가능성이 높습니다.<br>\r\n");
      out.write("			단, 접종 후 39℃ 이상의 고열이 나거나, 2일 이상 증상이 지속될 경우에는 의사의 진료가 필요합니다.<br>\r\n");
      out.write("			1단계 : 38.4℃ 이하 / 2단계 : 38.5℃~38.9℃ / 3단계 : 38.9℃~40℃ / 4단계 : 40.1 이상</p></font></li>\r\n");
      out.write("		<li><font size=\"4\">접종부위 통증\r\n");
      out.write("			<p>접종 당일에서 다음날까지는 접종부위가 불편하고 뻐근한 느낌이 들며, 예방접종 이후 나타날 수 있는 염증반응 입니다.<br>\r\n");
      out.write("			1단계 : 통증이 나타나지만 약을 복용할 정도는 아님 <br>\r\n");
      out.write("			2단계 : 1~2일 약물을 먹어야 팔을 움직이는데 지장이 없음<br>\r\n");
      out.write("			3단계 : 3일 이상 통증이 지속되거나 약을 먹어도 통증 조절이 안도어 팔을 움직이기 어려운 경우<br>\r\n");
      out.write("			(3단계는 의사의 진료가 필요합니다.)</p></font></li>\r\n");
      out.write("		<li><font size=\"4\">접종 부위 붓기 또는 발적 증상\r\n");
      out.write("			<p>접종 부위에 피부색으 변화 없이 부은 느낌이 들거나 실제 부었더라도 활동에 지장이 없는 경우 수일 내 자연적으로\r\n");
      out.write("			호전되는 접종 반응 중 하나입니다. <br>\r\n");
      out.write("			1단계 : 직경 5cm 이하 <br>\r\n");
      out.write("			2단계 : 직경 5.1cm~10cm, 움직이기 불편한 경우<br>\r\n");
      out.write("			3단계 : 직경 10cm 이상으로 부었거나 활동이 어려운 경우<br>\r\n");
      out.write("			4단계 : 접종 부위 피부색이 검게 또는 보라색 등 어둡게 변한 경우<br>\r\n");
      out.write("			(4단계는 의사의 진료가 필요합니다.<br>\r\n");
      out.write("			단계와 상관없이 이러한 증상이 3일 이상 지속되거나 접종부위의 피부색이 검게 또는 보라색으로 어둡게 변한다면\r\n");
      out.write("			의사의 진료가 필요합니다.</p></font></li>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<hr width=\"40%\" align=\"left\">\r\n");
      out.write("	<h4>3. 이상반응 나타날 시 대처법</h4>\r\n");
      out.write("	<img src=\"../../resources/images/vaccination06.png\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><font size=\"4\"><p>이상반응이 일상생활을 방해하지 않는 정도일 경우에는 의료기관을 방문하여 진료를 받을 수 있습니다.<br>\r\n");
      out.write("		하지만 아나필락시스 등의 심한 알레르기 반응이 나타날 경우에는 즉시 119로 연락하여 가까운 응급실로 내원해야 합니다.</p></font></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<p><a href=\"#top\">맨 위로 이동</a></p>\r\n");
      out.write("<hr>\r\n");
      out.write("                <!-- /# row -->\r\n");
      out.write("                <section id=\"main-content\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-12\">\r\n");
      out.write("                            <div id=\"extra-area-chart\"></div>\r\n");
      out.write("                            <div id=\"morris-line-chart\"></div>\r\n");
      out.write("                            <div class=\"footer\">\r\n");
      out.write("                                <p>2018 © Admin Board. -\r\n");
      out.write("                                    <a href=\"#\">example.com</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("    <!-- jquery vendor -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/jquery.nanoscroller.min.js\"></script>\r\n");
      out.write("    <!-- nano scroller -->\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/menubar/sidebar.js\"></script>\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/preloader/pace.min.js\"></script>\r\n");
      out.write("    <!-- sidebar -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- bootstrap -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/semi/resources/js/lib/bootstrap.min.js\"></script><script src=\"assets/js/scripts.js\"></script>\r\n");
      out.write("    <!-- scripit init-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
